tutorial/alunos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('homeMaterias/', views.homeMaterias, name="homeMaterias"),
    path('cadastrarMateria/', views.cadastrarMateria, name="cadastrarMateria"),
    path('editarMateria/', views.editarMateria, name="editarMateria"),
    path('alterarMateria/', views.alterarMateria, name="alterarMateria"),
    path('editarMateria/<int:materia_id>/', views.editarMateria, name="editarMateria"),
    path('deleteMateria/<int:materia_id>/', views.deleteMateria, name="deleteMateria"),
    path('salvarAlteracoesMateria/<int:materia_id>/', views.salvarAlteracoesMateria, name="salvarAlteracoesMateria"),
    path('usuariosMaterias/', views.usuariosMaterias, name="usuariosMaterias"),
    path('salvarUsuariosMaterias/', views.salvarUsuariosMaterias, name="salvarUsuariosMaterias"),
    path('listarUsuariosMaterias/', views.listarUsuariosMaterias, name="listarUsuariosMaterias"),
    path('viewNotasUsuarios/', views.viewNotasUsuarios, name="viewNotasUsuarios"),
    path('filtrarNotasUsuarioData/', views.filtrarNotasUsuarioData, name="filtrarNotasUsuarioData"),
    path('filtrarNotasUsuario/', views.filtrarNotasUsuario, name="filtrarNotasUsuario"),
    path('listarMateriasNotas/', views.listarMateriasNotas, name="listarMateriasNotas"),
    path('deleteUsuarioMateria/<slug:username>/', views.deleteUsuarioMateria, name="deleteUsuarioMateria"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('editarMateriaUsuario/<slug:username>/', views.editarMateriaUsuario, name="editarMateriaUsuario"),
    path('salvarUserMaterias/<slug:username>/', views.salvarUserMaterias, name="salvarUserMaterias"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('criarPergunta/', views.criarPergunta, name="criarPergunta"),
    path('inserirPergunta/', views.inserirPergunta, name="inserirPergunta"),
    path('listarPerguntasMateria/', views.listarPerguntasMateria, name="listarPerguntasMateria"),
    path('listarPerguntas/', views.listarPerguntas, name="listarPerguntas"),
    path('editarPergunta/<int:pergunta_id>/', views.editarPergunta, name="editarPergunta"),
    path('deletePergunta/<int:materia_id>/<int:pergunta_id>/', views.deletePergunta, name="deletePergunta"),
    path('salvarAlteracoesPergunta/<int:pergunta_id>/', views.salvarAlteracoesPergunta, name="salvarAlteracoesPergunta"),
    path('listarMateriasProva/', views.listarMateriasProva, name="listarMateriasProva"),
    path('listarAlunosMateria/', views.listarAlunosMateria, name="listarAlunosMateria"),
    path('criarProva/', views.criarProva, name="criarProva"),
    path('viewProvasAlunos/', views.viewProvasAlunos, name="viewProvasAlunos"),
    path('deleteProva/<int:materia_id>/<slug:usuario>/', views.deleteProva, name="deleteProva"),
    path('inicioProvaAluno/', views.inicioProvaAluno, name="inicioProvaAluno"),
    path('salvarProva/', views.salvarProva, name="salvarProva"),
    path('listarPerguntasProva/', views.listarPerguntasProva, name="listarPerguntasProva"),
    path('concluirProva/<nome_materia>/', views.concluirProva, name="concluirProva"),
    path('verProvaAluno/<int:materia_id>/<slug:usuario>/', views.verProvaAluno, name="verProvaAluno"),
    path('salvarCorrecoes/', views.salvarCorrecoes, name="salvarCorrecoes"),
    path('salvarNotaUsuario/<data>/<slug:aluno>/<int:prova_id>/', views.salvarNotaUsuario, name="salvarNotaUsuario"),
    path('arquivarProva/<int:materia_id>/<slug:aluno>/', views.arquivarProva, name="arquivarProva"),
    path('viewProvasHistory/', views.viewProvasHistory, name="viewProvasHistory"),
    path('mostrarDetalhesProva/<int:prova_id>/', views.mostrarDetalhesProva, name="mostrarDetalhesProva"),
    path('filtrarMateriaHistory/', views.filtrarMateriaHistory, name="filtrarMateriaHistory"),
    path('filtrarProvaAluno/', views.filtrarProvaAluno, name="filtrarProvaAluno")
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import home
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('alunos/', include('alunos.urls')),
    path('tutorial/', home),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('principal/', include('principal.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('usuarios/login/', include('django.contrib.auth.urls'), name='login'),
    prefix_default_language=True,
)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/alunos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Materia(models.Model):
    nome = models.CharField(max_length=30)
    nota_minima = models.FloatField(blank=True, null=True)
    nota_maxima = models.FloatField(blank=True, null=True)
    img_materia = models.FileField(upload_to='alunos/alunos.images', blank=True, null=True)

class AlunoMateria(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    materias = models.CharField(max_length=300, null=True, blank=True)

class AlunoMateriaNota(models.Model):
    prova_id = models.IntegerField()
    user_id = models.IntegerField()
    username = models.CharField(max_length=30, null=True, blank=True)
    materia = models.CharField(max_length=30, null=True, blank=True)
    nota = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    data = models.DateField(null=True, blank=True)

class Perguntas(models.Model):
    materia_id = models.IntegerField()
    nr_pergunta = models.IntegerField()
    pergunta = models.CharField(max_length=1000, null=True, blank=True)
    peso = models.IntegerField(blank=True, null=True)

class Respostas(models.Model):
    prova_id = models.IntegerField()
    data = models.DateField(blank=True, null=True)
    materia_id = models.IntegerField()
    pergunta_id = models.IntegerField()
    resposta = models.CharField(max_length=1000, null=True, blank=True)
    usuario = models.CharField(max_length=30)
    status = models.CharField(max_length=20, null=True, blank=True, default="Criada")
    resultado = models.CharField(max_length=20, null=True, blank=True)
    nota = models.IntegerField(blank=True, null=True)

class RespostasHistory(models.Model):
    prova_id = models.IntegerField()
    data = models.DateField(blank=True, null=True)
    materia_id = models.IntegerField()
    pergunta_id = models.IntegerField()
    nr_pergunta = models.IntegerField()
    pergunta = models.CharField(max_length=1000, null=True, blank=True)
    resposta = models.CharField(max_length=1000, null=True, blank=True)
    user_id = models.IntegerField()
    resultado = models.CharField(max_length=20, null=True, blank=True)
    peso = models.IntegerField(blank=True, null=True)

class ProvasHistory(models.Model):
    prova_id = models.IntegerField()
    user_id = models.IntegerField()
    materia_id = models.IntegerField()
    qtde_perguntas = models.IntegerField()
    status = models.CharField(max_length=30)
    nota = models.IntegerField(null=True, blank=True)

class view_materias_usuarios(models.Model):
    usuario_id = models.IntegerField()
    username = models.CharField(max_length=30)
    materias = models.CharField(max_length=300)
    class Meta:
        managed = False
        db_table = 'view_materias_usuarios'

class view_notasusuarios(models.Model):
    user_id = models.IntegerField()
    username = models.CharField(max_length=30)
    materia_id = models.IntegerField()
    data = models.DateField()
    materia = models.CharField(max_length=30)
    nota = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    nota_minima = models.FloatField(blank=True, null=True)
    nota_maxima = models.FloatField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'view_notasusuarios'

class view_perguntas_materia(models.Model):
    materia_id = models.IntegerField()
    nr_pergunta = models.IntegerField()
    pergunta = models.CharField(max_length=1000, null=True, blank=True)
    nome_materia = models.CharField(max_length=30, null=True, blank=True)
    peso = models.IntegerField(null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'view_perguntas_materia'

class view_provas(models.Model):
    prova_id = models.IntegerField()
    usuario = models.CharField(max_length=30)
    user_id = models.IntegerField()
    data = models.DateField()
    materia_id = models.IntegerField()
    nome_materia = models.CharField(max_length=30)
    pergunta_id = models.IntegerField()
    nr_pergunta = models.IntegerField()
    peso = models.IntegerField()
    pergunta = models.CharField(max_length=1000, null=True, blank=True)
    resposta = models.CharField(max_length=1000, null=True, blank=True)
    status = models.CharField(max_length=30, null=True, blank=True)
    resultado = models.CharField(max_length=30, null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'view_provas'

class view_provas_resumo(models.Model):
    prova_id = models.IntegerField()
    usuario = models.CharField(max_length=30)
    user_id = models.IntegerField()
    materia_id = models.IntegerField()
    nome_materia = models.CharField(max_length=30)
    qtde_perguntas = models.IntegerField()
    status = models.CharField(max_length=30)
    nota = models.IntegerField(null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'view_provas_resumo'

class view_provas_resumo_history(models.Model):
    prova_id = models.IntegerField()
    user_id = models.IntegerField()
    username = models.CharField(max_length=30)
    materia_id = models.IntegerField()
    nome_materia = models.CharField(max_length=30)
    status = models.CharField(max_length=30)
    nota = models.IntegerField(null=True, blank=True)
    qtde_perguntas = models.IntegerField()
    nota_minima = models.FloatField(blank=True, null=True)
    nota_maxima = models.FloatField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'view_provas_resumo_history'

class view_provas_history(models.Model):
    prova_id = models.IntegerField()
    user_id = models.IntegerField()
    data = models.DateField()
    username = models.CharField(max_length=30)
    materia_id = models.IntegerField()
    nome_materia = models.CharField(max_length=30)
    pergunta_id = models.IntegerField()
    nr_pergunta = models.IntegerField()
    peso = models.IntegerField()
    pergunta = models.CharField(max_length=1000, null=True, blank=True)
    resposta = models.CharField(max_length=1000, null=True, blank=True)
    status = models.CharField(max_length=30)
    nota = models.IntegerField(null=True, blank=True)
    resultado = models.CharField(max_length=30, null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'view_provas_history'

tutorial/alunos/forms.py
from django import forms
from .models import Materia, AlunoMateria, AlunoMateriaNota


class MateriaForm(forms.ModelForm):
    class Meta:
        model = Materia
        fields = [
            'nome',
            'nota_minima',
            'nota_maxima',
        ]

class AlunoMateriaForm(forms.ModelForm):
    class Meta:
        model = AlunoMateria
        fields = [
            'usuario',
            'materias'
        ]

tutorial/alunos/templates/agendarProva.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Criar Prova Aluno" %} </title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 style="color:blue;"> {{ mensagem }} <h3>
  <form method="post" action="{% url 'criarProva' %}">
    {% csrf_token %}
      <p><label>{% trans "Matéria" %}:</label> <input readonly=True type="text" name="nome_materia" value="{{ nome_materia }}" </p>
        <p><label>{{ alunos }}</label> <ul id="id_materias">
          {% for aluno in list_alunos %}
              <li><label for="id_aluno"><input type="checkbox" name="aluno" value="{{ aluno }}" id="id_aluno">
                {{ aluno }}</label>
              </li>
          {% endfor %}
        </ul> <button type="submit"> {% trans "Criar Prova" %} </button>
   </form>
</div>
{% endblock %}

tutorial/alunos/templates/alterarMateria.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block body %}
<div class="container">
  <h2 style="color:blue;"> {{ mensagem }} </h2>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">{% trans "Nome Matéria" %}</th>
      <th scope="col">{% trans "Nota Mínima" %}</th>
      <th scope="col">{% trans "Nota Máxima" %}</th>
      <th scope="col">{% trans "Imagem" %}</th>
      <th scope="col">{% trans "Editar" %}</th>
      <th scope="col">{% trans "Remover" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for materia in materias %}
          <tr>
            <td>{{ materia.nome }}</td>
            <td>{{ materia.nota_minima }}</td>
            <td>{{ materia.nota_maxima }}</td>
            {% if materia.img_materia %}
                  <td><img width="50px" height="50px" src="{{materia.img_materia.url}}"/></td>
            {% else %}
              <td></td>
            {% endif %}
            <td> <a href="{% url 'editarMateria' materia.id %}"> <img width="30px" height="30px" src="{% static 'images/editar.jpg' %}"/> </a> </td>
            <td> <a href="{% url 'deleteMateria' materia.id %}"> <img width="20px" height="20px" src="{% static 'images/cancel.png' %}"/> </a> </td>
          </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

tutorial/alunos/templates/editarMateriaUsuario.html
{% extends 'base2.html' %}
{% load i18n %}

{% block head %}
<title> {% trans "Usuários Matérias" %} </title>
{% endblock %}

{% block body %}
<div class="container">
<h1> {% trans "Usuários Matérias" %} </h1>
<form method="post" action="{% url 'salvarUserMaterias' username %}" enctype="multipart/form-data">
  {% csrf_token %}
  <p><label for="usuario"> {% trans "Selecione um usuário" %} </label><select name="usuario" style="font-size:24px;">
    <option value="{{ user_id }}" selected>{{ username }}</option>
  </select></p> </br>
  <p><label>{% trans "Matérias" %}:</label> <ul id="id_materias">
    {% for materia in materias %}
      {% if materia.nome in lista_materias %}
        <li><label for="id_materias"><input type="checkbox" name="materias" value="{{ materia.id }}" id="id_materia" checked>
          {{ materia.nome }}</label>
        </li>
      {% else %}
        <li><label for="id_materias"><input type="checkbox" name="materias" value="{{ materia.id }}" id="id_materia">
          {{ materia.nome }}</label>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
    <button type="submit"> Salvar </button>
  </form>
</div>
{% endblock %}

tutorial/alunos/templates/editarPergunta.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Editar Pergunta" %} </title>
{% endblock %}

{% block body %}
<div class="container">
   <h3 style="color:blue;"> {{ mensagem }} </h3>
    <label for="materia"> {% trans "Matéria" %}: {{ nome_materia }} </label>
    <form method="post" action="{% url 'salvarAlteracoesPergunta' materia.id %}">
      {% csrf_token %}
      <p> <label for="id_nr_pergunta"> {% trans "Número Pergunta" %} </label> <input type="number" min=1 style="width: 3em;" name="nr_pergunta" id="id_nr_pergunta" value="{{ materia.nr_pergunta }}"> </p>
      <p> <label for="id_peso"> {% trans "Peso" %}: </label> <input type="number" style="width: 3em;" min=1 max=10 name="peso" id="id_peso" value="{{ materia.peso }}"> </p>
      <p> <label for="id_pergunta">{% trans "Pergunta" %}:</label> <textarea name="pergunta" maxlength="1000" rows="3" cols="100"> {{ materia.pergunta }} </textarea> </p>
      <button type="submit"> {% trans "Salvar" %} </button>
    </form>
</div>
{% endblock %}

tutorial/alunos/templates/homeMaterias.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Home Materias" %} </title>
{% endblock %}

{% block body %}
<div class="container">
{% for materia in materias %}
    {% if materia.img_materia %}
          <div class="prod-menu">
            <a href="{% url 'viewMateriasUsuario' materia.id %}"> <h3> {{ materia.nome }} </h3> <img src="{{ materia.img_materia.url }}" class="box-menu img">  </a>
          </div>
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

tutorial/alunos/templates/inicioProvaAluno.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Início Prova Aluno" %} </title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 style="color:blue;"> {{ mensagem }} <h3>
    {% if request.user.is_authenticated %}
          <form method="post" action="{% url 'listarPerguntasProva' %}">
            {% csrf_token %}
              <p> <label>{% trans "Aluno" %}:</label> {{ request.user.username }} </p>
              <p><label>{% trans "Escolha a matéria que deseja realizar a prova" %}:</label>
                <select name="materia" style="font-size:24px;">
                  <option value="" selected>{% trans "Selecione uma matéria" %}</option>
                   {% for materia in materias %}
                      <option value="{{ materia.materia_id }}"> {{ materia.nome_materia }} </option>
                   {% endfor %}
                </select>
               <button type="submit"> {% trans "Ver Prova" %} </button> </p>
           </form>
    {% endif %}
</div>
{% endblock %}

tutorial/alunos/templates/listarMateriasProva.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Listar Alunos Matéria" %} </title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 style="color:blue;"> {{ mensagem }} <h3>
  <form method="post" action="{% url 'listarAlunosMateria' %}">
    {% csrf_token %}
      <p><label>{% trans "Matérias" %}:</label>
        <select name="materia" style="font-size:24px;">
          <option value="" selected>{% trans "Selecione uma matéria" %}</option>
           {% for materia in materias %}
              <option value="{{ materia.id }}"> {{ materia.nome }} </option>
           {% endfor %}
        </select>
        <button type="submit"> {% trans "Listar Alunos" %} </button> <p>
   </form>
</div>
{% endblock %}

tutorial/alunos/templates/listarUsuariosMaterias.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Listar Notas Usuários" %} </title>
{% endblock %}

{% block body %}
<div class="container">
  <h1> {% trans "Listar Notas Usuários" %} </h1>
  <h2 style="color:blue;"> {{ mensagem }} </h2>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">{% trans "Usuário" %}</th>
      <th scope="col">{% trans "Matérias" %}</th>
      <th scope="col">{% trans "Editar" %}</th>
      <th scope="col">{% trans "Excluir" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for materia in viewMateriasUsuario %}
          <tr>
            <td>{{ materia.username }}</td>
            <td>{{ materia.materias }}</td>
            <td> <a href="{% url 'editarMateriaUsuario' materia.username %}"> <img width="30px" height="30px" src="{% static 'images/editar.jpg' %}"/> </a> </td>
            <td> <a href="{% url 'deleteUsuarioMateria' materia.username %}"> <img width="20px" height="20px" src="{% static 'images/cancel.png' %}"/> </a> </td>
          </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

tutorial/alunos/templates/verNotasUsuarioMateria.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block body %}
<div class="container">
  <img src="{{ materia.img_materia.url }}" height="100px;" width="100px;"> <label for="img_materia"> {{materia.nome}}
    <h2 style="color:blue;"> {{ mensagem }} </h2>
    <p> {% trans "Usuário" %} {{ request.user.username }} </p>
    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">{% trans "Data" %}</th>
        <th scope="col">{% trans "Matéria" %}</th>
        <th scope="col">{% trans "Nota" %}</th>
        <th scope="col">{% trans "Resultado" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for nota in viewUsuariosNotas %}
          <tr>
            <td>{{ nota.data }}</td>
            <td>{{ nota.materia }}</td>
            <td>{{ nota.nota }}</td>
            {% if nota.nota < nota.nota_minima %}
                <td style="color:red;">{% trans "Falhou" %}</td>
            {% else %}
                <td>{% trans "Passou" %}</td>
            {% endif %}
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

tutorial/alunos/templates/viewAlunoProva.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Lista Perguntas Matéria" %} </title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 style="color:blue;"> {{ mensagem }} <h3>
   <table class="table">
   <thead class="thead-dark">
     <tr>
      <th scope="col">{% trans "Data" %}</th>
      <th scope="col">{% trans "Aluno" %}</th>
      <th scope="col">{% trans "Matéria" %}</th>
      <th scope="col">{% trans "Status" %}</th>
      <th scope="col">{% trans "Total Peso" %}</th>
      <th scope="col">{% trans "Incluir Nota Aluno" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for resposta in respostas %}
    <tr>
      <form method="post" action="{% url 'salvarNotaUsuario' data resposta.usuario resposta.prova_id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <td>{{ data }}</td>
        <td>{{ resposta.usuario }}</td>
        <td> <label for="nome_materia"> <input type="text" name="materia" value="{{ resposta.nome_materia }}" hidden> {{ resposta.nome_materia }} </label></td>
        <td>{{ resposta.status }}</td>
        <td>{{ resposta.total_peso }}</td>
        <td> <label for="nota"> <input type="number" min=0 max=10 name="nota" style="width: 3em;" value="{{ resposta.nota }}"> </label> </td>
    </tr>
    {% endfor %}
    <tr> <td>  <button type="submit"> {% trans "Salvar Notas" %} </button> </td> </tr>
  </form>
  </tbody>
</table>
</div>
{% endblock %}

tutorial/alunos/templates/viewDetalhesProva.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "View Provas History" %} </title>
{% endblock %}

{% block body %}
<div class="container">
  <h3 style="color:blue;"> {{ mensagem }} <h3>
   <table class="table">
   <thead class="thead-dark">
     <tr>
       <th scope="col">{% trans "Aluno" %}</th>
       <th scope="col">{% trans "Matéria" %}</th>
       <th scope="col">{% trans "Qtde. Perguntas" %}</th>
       <th scope="col">{% trans "Status" %}</th>
       <th scope="col">{% trans "Nota" %}</th>
       <th scope="col">{% trans "Resultado" %}</th>
     </tr>
   </thead>
   <tbody>
       <tr>
         {% for prova in provas %}
             <td> <a href="{% url 'viewProvasHistory' %}">{{ prova.username }} </a> </td>
             <td>{{ prova.nome_materia }}</td>
             <td>{{ prova.qtde_perguntas }}</td>
             <td>{{ prova.status }}</td>
             <td>{{ prova.nota }}</td>
             {% if prova.nota < prova.nota_minima %}
                 <td style="color:red;">{% trans "Falhou" %}</td>
             {% else %}
                 <td>{% trans "Passou" %}</td>
             {% endif %}
        {% endfor %}
       </tr>
   </tbody>
   <thead class="thead-dark">
     <tr>
       <th scope="col">{% trans "Data" %}</th>
       <th scope="col">{% trans "Nr. Pergunta" %}</th>
       <th scope="col" colspan="2">{% trans "Pergunta" %}</th>
       <th scope="col">{% trans "Peso" %}</th>
       <th scope="col">{% trans "Resposta" %}</th>
       <th scope="col">{% trans "Resultado" %}</th>
     </tr>
   </thead>
   <tbody>
         {% for resultado in resultados %}
         <tr>
             <td> {{ resultado.data }} </td>
             <td>{{ resultado.nr_pergunta }}</td>
             <td colspan="2">{{ resultado.pergunta }}</td>
             <td>{{ resultado.peso }}</td>
             <td>{{ resultado.resposta }}</td>
             <td>{{ resultado.resultado }}</td>
        </tr>
        {% endfor %}
   </tbody>
 </table>
</div>
{% endblock %}

tutorial/alunos/templates/viewNotasUsuarios.html
{% extends 'base2.html' %}
{% load static %}
{% load i18n %}

{% block body %}
<div class="container">
  <h2 style="color:blue;"> {{ mensagem }} </h2>
  <form method="POST" action="{% url 'filtrarNotasUsuarioData' %}">
       {% csrf_token %}
      <select name="data" style="font-size:24px;">
        <option disabled="true" selected> --{% trans "Selecione uma Data" %}-- </option>
         {% for data in datas %}
            <option value="{{ data.data }}"> {{ data.data }} </option>
         {% endfor %}
      </select>
      <button type="submit"> {% trans "Filtrar" %} </button>
  </form>
  <form method="POST" action="{% url 'filtrarNotasUsuario' %}">
       {% csrf_token %}
      <select name="user" style="font-size:24px;">
        <option disabled="true" selected> --{% trans "Selecione um Usuário" %}-- </option>
         {% for usuario in usuarios %}
            <option value="{{ usuario.user_id }}"> {{ usuario.username }} </option>
         {% endfor %}
      </select>
      <button type="submit"> {% trans "Filtrar" %} </button>
  </form>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">{% trans "Data" %}</th>
      <th scope="col">{% trans "Usuário" %}</th>
      <th scope="col">{% trans "Matéria" %}</th>
      <th scope="col">{% trans "Nota" %}</th>
      <th scope="col">{% trans "Resultado" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for nota in viewNotas %}
          <tr>
            <td>{{ nota.data }}</td>
            <td>{{ nota.username }}</td>
            <td>{{ nota.materia }}</td>
            <td>{{ nota.nota }}</td>
            {% if nota.nota < nota.nota_minima %}
                <td style="color:red;">{% trans "Falhou" %}</td>
            {% else %}
                <td>{% trans "Passou" %}</td>
            {% endif %}
          </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}