tutorial/alunos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('homeMaterias/', views.homeMaterias, name="homeMaterias"),
    path('cadastrarMateria/', views.cadastrarMateria, name="cadastrarMateria"),
    path('editarMateria/', views.editarMateria, name="editarMateria"),
    path('alterarMateria/', views.alterarMateria, name="alterarMateria"),
    path('editarMateria/<int:materia_id>/', views.editarMateria, name="editarMateria"),
    path('deleteMateria/<int:materia_id>/', views.deleteMateria, name="deleteMateria"),
    path('salvarAlteracoesMateria/<int:materia_id>/', views.salvarAlteracoesMateria, name="salvarAlteracoesMateria"),
    path('usuariosMaterias/', views.usuariosMaterias, name="usuariosMaterias"),
    path('salvarUsuariosMaterias/', views.salvarUsuariosMaterias, name="salvarUsuariosMaterias"),
    path('listarUsuariosMaterias/', views.listarUsuariosMaterias, name="listarUsuariosMaterias"),
    path('viewNotasUsuarios/', views.viewNotasUsuarios, name="viewNotasUsuarios"),
    path('filtrarNotasUsuarioData/', views.filtrarNotasUsuarioData, name="filtrarNotasUsuarioData"),
    path('filtrarNotasUsuario/', views.filtrarNotasUsuario, name="filtrarNotasUsuario"),
    path('listarMateriasNotas/', views.listarMateriasNotas, name="listarMateriasNotas"),
    path('deleteUsuarioMateria/<slug:username>/', views.deleteUsuarioMateria, name="deleteUsuarioMateria"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('editarMateriaUsuario/<slug:username>/', views.editarMateriaUsuario, name="editarMateriaUsuario"),
    path('salvarUserMaterias/<slug:username>/', views.salvarUserMaterias, name="salvarUserMaterias"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('criarPergunta/', views.criarPergunta, name="criarPergunta"),
    path('inserirPergunta/', views.inserirPergunta, name="inserirPergunta"),
    path('listarPerguntasMateria/', views.listarPerguntasMateria, name="listarPerguntasMateria"),
    path('listarPerguntas/', views.listarPerguntas, name="listarPerguntas"),
    path('editarPergunta/<int:pergunta_id>/', views.editarPergunta, name="editarPergunta"),
    path('deletePergunta/<int:materia_id>/<int:pergunta_id>/', views.deletePergunta, name="deletePergunta"),
    path('salvarAlteracoesPergunta/<int:pergunta_id>/', views.salvarAlteracoesPergunta, name="salvarAlteracoesPergunta"),
    path('listarMateriasProva/', views.listarMateriasProva, name="listarMateriasProva"),
    path('listarAlunosMateria/', views.listarAlunosMateria, name="listarAlunosMateria"),
    path('criarProva/', views.criarProva, name="criarProva"),
    path('viewProvasAlunos/', views.viewProvasAlunos, name="viewProvasAlunos"),
    path('deleteProva/<int:materia_id>/<slug:usuario>/', views.deleteProva, name="deleteProva"),
    path('inicioProvaAluno/', views.inicioProvaAluno, name="inicioProvaAluno"),
    path('salvarProva/', views.salvarProva, name="salvarProva"),
    path('listarPerguntasProva/', views.listarPerguntasProva, name="listarPerguntasProva"),
    path('concluirProva/<nome_materia>/', views.concluirProva, name="concluirProva"),
    path('verProvaAluno/<int:materia_id>/<slug:usuario>/', views.verProvaAluno, name="verProvaAluno"),
    path('salvarCorrecoes/', views.salvarCorrecoes, name="salvarCorrecoes"),
    path('salvarNotaUsuario/<data>/<slug:aluno>/<int:prova_id>/', views.salvarNotaUsuario, name="salvarNotaUsuario"),
    path('arquivarProva/<int:materia_id>/<slug:aluno>/', views.arquivarProva, name="arquivarProva"),
    path('viewProvasHistory/', views.viewProvasHistory, name="viewProvasHistory"),
    path('mostrarDetalhesProva/<int:prova_id>/', views.mostrarDetalhesProva, name="mostrarDetalhesProva"),
    path('filtrarMateriaHistory/', views.filtrarMateriaHistory, name="filtrarMateriaHistory"),
    path('filtrarProvaAluno/', views.filtrarProvaAluno, name="filtrarProvaAluno")
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import home
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('alunos/', include('alunos.urls')),
    path('tutorial/', home),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('principal/', include('principal.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('usuarios/login/', include('django.contrib.auth.urls'), name='login'),
    prefix_default_language=True,
)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/usuarios/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from . classes import password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
    path('login_user/', views.login_user, name="login_user"),
    path('cadastrarUsuario/', views.cadastrarUsuario, name="cadastrarUsuario"),
    path('logout/', views.user_logout, name="user_logout"),
    path('alterarSenha/', views.alterarSenha, name="alterarSenha"),
    path('resetPassword/', password_reset, name="resetPassword"),
    path('resetPassword/password_reset_done/', password_reset_done, name="password_reset_done"),
    path('reset/<uidb64>/<token>/', password_reset_confirm, name="password_reset_confirm"),
    path('reset/done/', password_reset_complete, name="password_reset_complete"),
    path('cadastrarPerfil/', views.cadastrarPerfil, name="cadastrarPerfil"),
    path('editarPerfil/', views.editarPerfil, name="editarPerfil"),
    path('salvarAlteracoesUsuario/<slug:username>/', views.salvarAlteracoesUsuario, name="salvarAlteracoesUsuario"),
    path('salvarGrupoUsuario/', views.salvarGrupoUsuario, name="salvarGrupoUsuario"),
    path('listarUsuarios/', views.listarUsuarios, name="listarUsuarios"),
    path('editarUsuario/<int:user_id>/', views.editarUsuario, name="editarUsuario"),
    path('deleteUsuario/<int:user_id>/', views.deleteUsuario, name="deleteUsuario"),
    path('salvarAlteracoesUser/<int:user_id>/', views.salvarAlteracoesUser, name="salvarAlteracoesUser")
]

tutorial/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from  django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    telefone = models.IntegerField(null=True, blank=True)
    endereco_completo = models.CharField(max_length=500, blank=True, null=True)
    idade = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return str(self.user)

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

class view_grupos(models.Model):
    id_grupo = models.IntegerField(null=True, blank=True)
    nome = models.CharField(max_length=15, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'view_grupos'

class view_user_grupo(models.Model):
    user_id = models.IntegerField(null=True, blank=True)
    username = models.CharField(max_length=20, blank=True, null=True)
    grupo_id = models.IntegerField(null=True, blank=True)
    nome_grupo = models.CharField(max_length=15, blank=True, null=True)
    first_name = models.CharField(max_length=20, blank=True, null=True)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'view_user_grupo'

tutorial/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import UserProfile


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
        'username',
        'first_name',
        'last_name',
        'email',
        'password1',
        'password2',
        ]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = [
            'user',
            'telefone',
            'endereco_completo',
            'idade',
        ]

tutorial/usuarios/views.py
from django.shortcuts import render, redirect
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.contrib import auth
from .forms import RegistrationForm
from django.contrib.auth import logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import UserProfileForm
from .models import UserProfile, view_user_grupo
from .functions import (getGrupos, associarGrupoUsuario, getUserGrupo, deleteGrupoUsuario, getAllGrupos,
    getAllUsers, getAllUsersRestaurante, getAllUsersEscola, getUsuario, removerUsuario, checkUserMateria, checkUserProva,
    checkUserPedido)
from principal.functions import getIdiomaSystem
from django.conf.urls.i18n import i18n_patterns
from django.utils import translation


def login_user(request):
    idioma = getIdiomaSystem(request)
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        auth.login(request, user)
        idioma = translation.get_language()
        return redirect("/" + idioma + "/tutorial/")
    context = {
        'idioma': idioma,
    }
    return render(request, "loginUser.html", context)

def cadastrarUsuario(request):
    grupos = getAllGrupos(request)
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get("username")
            grupo = request.POST.get("grupo")
            usuario = User.objects.get(username=username)
            user_id = usuario.id
            criarGrupo = associarGrupoUsuario(request, user_id, grupo)
            return render(request, "index.html")
        else:
            form = RegistrationForm()
            context = {
                'form': form,
                'grupos': grupos
            }
            return render(request, "cadastrarUsuario.html", context)
    else:
        form = RegistrationForm()
        context = {
            'form': form,
            'grupos': grupos
        }
        return render(request, "cadastrarUsuario.html", context)

def user_logout(request):
    print("entrou no logout")
    logout(request)
    idioma = translation.get_language()
    return redirect("/" + idioma + "/tutorial/")

def alterarSenha(request):
    idioma = getIdiomaSystem(request)
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return render(request, "index.html")
        else:
            return redirect('/tutorial/')
    else:
        form = PasswordChangeForm(user=request.user)
        context = {
	     'form': form,
         'idioma': idioma
	}
    return render(request, "alterarSenha.html", context)

def cadastrarPerfil(request):
    idioma = getIdiomaSystem(request)
    form = UserProfileForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect('/tutorial/')
    else:
        print('form is not valid')
        print(form.errors)
    context = {
        'form': form,
        'idioma': idioma
    }
    return render(request, "cadastrarPerfil.html", context)

def editarPerfil(request):
    if request.user.is_authenticated:
        user = request.user
        user_id = request.user.id
        usuario = User.objects.get(username=user)
        profile = UserProfile.objects.get(user=user)
        user_grupo = getUserGrupo(request, user_id)
        grupo_id = user_grupo[0]['grupo_id']
        grupo_nome = user_grupo[0]['nome_grupo']
        grupos = getGrupos(request, grupo_id)
    else:
        usuario = ""
        profile = ""
    context = {
        'usuario': usuario,
        'profile': profile,
        'grupos': grupos,
        'grupo_id': grupo_id,
        'grupo_nome': grupo_nome
    }
    return render(request, "editarPerfil.html", context)

def salvarAlteracoesUsuario(request, username):
    usuario = User.objects.get(username=username)
    profile = UserProfile.objects.get(user=usuario.id)
    user = request.POST.get("user")
    first_name = request.POST.get("first_name")
    last_name = request.POST.get("last_name")
    email = request.POST.get("email")
    telefone = request.POST.get("telefone")
    endereco_completo = request.POST.get("endereco_completo")
    idade = request.POST.get("idade")
    usuario.username = username
    usuario.first_name = first_name
    usuario.last_name = last_name
    usuario.email = email
    usuario.save()
    profile.telefone = telefone
    profile.endereco_completo = endereco_completo
    profile.idade = idade
    profile.save()
    return redirect('/tutorial/')

def salvarGrupoUsuario(request):
    user_id = request.POST.get("user")
    grupo_id = request.POST.get("grupo")
    removeGrupo = deleteGrupoUsuario(request, user_id)
    criarGrupo = associarGrupoUsuario(request, user_id, grupo_id)
    logout(request)
    idioma = translation.get_language()
    return redirect("/" + idioma + "/usuarios/")

def listarUsuarios(request):
    user_id = request.user.id
    grupo = view_user_grupo.objects.get(user_id=user_id)
    grupo_nome = grupo.nome_grupo
    if grupo_nome == 'admin':
        usuarios = getAllUsersRestaurante(request)
    elif grupo_nome == 'professor':
        usuarios = getAllUsersEscola(request)
    else:
        usuarios = getAllUsers(request)
    context = {
        'usuarios': usuarios
    }
    return render(request, "listarUsuarios.html", context)

def editarUsuario(request, user_id):
    usuario = User.objects.get(id=user_id)
    profile = UserProfile.objects.get(user_id=user_id)
    user_grupo = getUserGrupo(request, user_id)
    grupo_id = user_grupo[0]['grupo_id']
    grupo_nome = user_grupo[0]['nome_grupo']
    grupos = getGrupos(request, grupo_id)
    context = {
        'usuario': usuario,
        'profile': profile,
        'grupo_id': grupo_id,
        'grupo_nome': grupo_nome,
        'grupos': grupos
    }
    return render(request, "editarUsuario.html", context)

def salvarAlteracoesUser(request, user_id):
    usuario = User.objects.get(id=user_id)
    profile = UserProfile.objects.get(user_id=user_id)
    user = request.POST.get("user")
    first_name = request.POST.get("first_name")
    last_name = request.POST.get("last_name")
    email = request.POST.get("email")
    telefone = request.POST.get("telefone")
    endereco_completo = request.POST.get("endereco_completo")
    idade = request.POST.get("idade")
    grupo = request.POST.get("grupo")
    removeGrupo = deleteGrupoUsuario(request, user_id)
    criarGrupo = associarGrupoUsuario(request, user_id, grupo)
    usuario.id = user
    usuario.first_name = first_name
    usuario.last_name = last_name
    usuario.email = email
    usuario.save()
    profile.telefone = telefone
    profile.endereco_completo = endereco_completo
    profile.idade = idade
    profile.save()
    usuarios = getAllUsers(request)
    context = {
        'usuarios': usuarios
    }
    return render(request, "listarUsuarios.html", context)

def deleteUsuario(request, user_id):
    mensagem = ""
    userGrupo = view_user_grupo.objects.get(user_id=user_id)
    nome_grupo = userGrupo.nome_grupo
    if nome_grupo == 'aluno':
        check = checkUserMateria(request, user_id)
        if check == []:
            usuario = User.objects.get(id=user_id)
            username = usuario.username
            check2 = checkUserProva(request, username)
            if check2 == []:
                removeUser = removerUsuario(request, user_id)
                mensagem = _("Usuário deletado com sucesso!")
            else:
                mensagem = _("Usuário não pode ser deletado pois está associado a uma prova!")
        else:
            mensagem = _("Usuário não pode ser deletado pois está associado a uma ou mais matérias")
    elif nome_grupo == 'usuario':
        check3 = checkUserPedido(request, user_id)
        if check3 == []:
            removeUser = removerUsuario(request, user_id)
            mensagem = _("Usuário deletado com sucesso!")
        else:
            mensagem = _("Usuário não pode ser deletado pois está associado a um ou mais pedidos")
    elif nome_grupo == 'admin' or nome_grupo == 'professor':
        mensagem = _("Usuário não pode ser deletado pois ele é admin")
    else:
        removeUser = removerUsuario(request, user_id)
        mensagem = _("Usuário deletado com sucesso!")
    usuarios = getAllUsers(request)
    context = {
        'usuarios': usuarios,
        'mensagem': mensagem
    }
    return render(request, "listarUsuarios.html", context)

tutorial/usuarios/templates/alterarSenha.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% endblock %}

{% block body %}
<div class="container">
    <h1> {% trans "Alterar Senha Usuário" %} </h1>
      <form method="POST">
        {% csrf_token %}
        <p><label for="id_old_password">{% trans "Antiga Senha" %}:</label> <input type="password" name="old_password" autofocus required id="id_old_password"></p>
        <p><label for="id_new_password1">{% trans "Nova Senha" %}:</label> <input type="password" name="new_password1" required id="id_new_password1"> </p>
        <p><label for="id_new_password2">{% trans "Confirmar Nova Senha" %}:</label> <input type="password" name="new_password2" required id="id_new_password2"></p>
          <button type="submit"> {% trans "Alterar Senha" %} </button>
      </form>
</div>
{% endblock %}

tutorial/usuarios/templates/cadastrarPerfil.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
<h1> Cadastrar Perfil do usuário </h1>
  <form method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <button type="submit"> Salvar </button>
  </form>
</div>
{% endblock %}

tutorial/usuarios/templates/cadastrarUsuario.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
      <h1> {% trans "Cadastro de Usuário" %} </h1>
        <p><label for="id_username">{% trans "Usuário" %}:</label> <input type="text" name="username" maxlength="150" autofocus required id="id_username"> <span class="helptext">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
        <p><label for="id_first_name">{% trans "Primeiro Nome" %}:</label> <input type="text" name="first_name" maxlength="30" id="id_first_name"></p>
        <p><label for="id_last_name">{% trans "Último Nome" %}:</label> <input type="text" name="last_name" maxlength="150" id="id_last_name"></p>
        <p><label for="id_email">{% trans "Email" %}:</label> <input type="email" name="email" maxlength="254" id="id_email"></p>
        <p><label for="id_password1">{% trans "Senha" %}:</label> <input type="password" name="password1" autocomplete="new-password" required id="id_password1"></p>
        <p><label for="id_password2">{% trans "Confirmação de Senha" %}:</label> <input type="password" name="password2" autocomplete="new-password" required id="id_password2"> <span class="helptext">Enter the same password as before, for verification.</span></p>
        <p><label for="id_grupo">{% trans "Grupo" %}:</label> <select name="grupo" required id="id_grupo">
            <option value="" selected>--------</option>
            {% for grupo in grupos %}
              <option value="{{ grupo.id_grupo }}"> {{grupo.nome }} </option>
            {% endfor %}
        </select></p>
            <button type="submit"> {% trans "Cadastrar" %} </button>
  </form>
</div>
{% endblock %}

tutorial/usuarios/templates/editarPerfil.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% endblock %}

{% block body %}
<div class="container">
  <h1> {% trans "Editar Perfil de Usuário" %} </h1>
    <form method="post" action="{% url 'salvarAlteracoesUsuario' usuario.username %}">
      {% csrf_token %}
      <p><label for="id_user">{% trans "Usuário" %}:</label> <select name="user" required id="id_user">
        <option value="{{ usuario.id }}" selected>{{ usuario.username }}</option>
      </select></p>
      <p><label for="id_first_name">{% trans "Primeiro Nome" %}:</label> <input type="text" name="first_name" maxlength="30" id="id_first_name" value="{{ usuario.first_name }}"></p>
      <p><label for="id_last_name">{% trans "Último Nome" %}:</label> <input type="text" name="last_name" maxlength="150" id="id_last_name" value="{{ usuario.last_name }}"></p>
      <p><label for="id_email">{% trans "Email" %}:</label> <input type="email" name="email" maxlength="254" id="id_email" value="{{ usuario.email }}"></p>
      <p><label for="id_telefone">{% trans "Telefone" %}:</label> <input type="number" name="telefone" id="id_telefone" value="{{ profile.telefone }}"></p>
      <p><label for="id_endereco_completo">{% trans "Endereço Completo" %}:</label> <input type="text" name="endereco_completo" maxlength="500" id="id_endereco_completo" value="{{ profile.endereco_completo }}"></p>
      <p><label for="id_idade">{% trans "Idade" %}:</label> <input type="number" name="idade" id="id_idade" value="{{ profile.idade}}"></p>
        <button type="submit"> {% trans "Salvar Alterações" %} </button>
    </form>
</div>
{% endblock %}

tutorial/usuarios/templates/editarUsuario.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
{% endblock %}

{% block body %}
<div class="container">
  <h1> {% trans "Editar Perfil de Usuário" %} </h1>
    <form method="post" action="{% url 'salvarAlteracoesUser' usuario.id %}">
      {% csrf_token %}
      <p><label for="id_user">{% trans "Usuário" %}:</label> <select name="user" required id="id_user">
        <option value="{{ usuario.id }}" selected>{{ usuario.username }}</option>
      </select></p>
      <p><label for="id_first_name">{% trans "Primeiro Nome" %}:</label> <input type="text" name="first_name" maxlength="30" id="id_first_name" value="{{ usuario.first_name }}"></p>
      <p><label for="id_last_name">{% trans "Último Nome" %}:</label> <input type="text" name="last_name" maxlength="150" id="id_last_name" value="{{ usuario.last_name }}"></p>
      <p><label for="id_email">{% trans "Email" %}:</label> <input type="email" name="email" maxlength="254" id="id_email" value="{{ usuario.email }}"></p>
      <p><label for="id_telefone">{% trans "Telefone" %}:</label> <input type="number" name="telefone" id="id_telefone" value="{{ profile.telefone }}"></p>
      <p><label for="id_endereco_completo">{% trans "Endereço Completo" %}:</label> <input type="text" name="endereco_completo" maxlength="500" id="id_endereco_completo" value="{{ profile.endereco_completo }}"></p>
      <p><label for="id_idade">{% trans "Idade" %}:</label> <input type="number" name="idade" id="id_idade" value="{{ profile.idade}}"></p>
      <p><label for="id_grupo">{% trans "Grupo" %}:</label> <select name="grupo" required id="id_grupo">
        <option value="{{ grupo_id }}" selected>{{ grupo_nome }}</option>
        {% for grupo in grupos %}
            <option value="{{grupo.id_grupo}}">{{grupo.nome}}</option>
        {% endfor %}
      </select></p>
        <button type="submit"> {% trans "Salvar Alterações" %} </button>
    </form>
</div>
{% endblock %}

tutorial/usuarios/templates/listarUsuarios.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
{% endblock %}

{% block body %}
<div class="container">
  <h3 style="color:blue;">{{ mensagem }} </h3>
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">{% trans "Usuário" %}</th>
      <th scope="col">{% trans "Primeiro Nome" %}</th>
      <th scope="col">{% trans "Último Nome" %}</th>
      <th scope="col">{% trans "Email" %}</th>
      <th scope="col">{% trans "Grupo" %}</th>
      <th scope="col">{% trans "Editar" %}</th>
      <th scope="col">{% trans "Excluir" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for usuario in usuarios %}
      <tr>
        <td>{{ usuario.username }}</td>
        <td>{{ usuario.first_name }}</td>
        <td>{{ usuario.last_name }}</td>
        <td>{{ usuario.email }}</td>
        <td>{{ usuario.nome_grupo }}</td>
        <td> <a href="{% url 'editarUsuario' usuario.user_id %}"> <img width="30px" height="30px" src="{% static 'images/editar.jpg' %}"/> </a> </td>
        <td> <a href="{% url 'deleteUsuario' usuario.user_id %}"> <img width="20px" height="20px" src="{% static 'images/cancel.png' %}"/> </a> </td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

tutorial/usuarios/templates/loginUser.html
{% extends 'base2.html' %}
{% load i18n %}

{% block content %}
{% endblock %}

{% block body %}
<div class="container">
  <form method="post">
    {% csrf_token %}
      <h2> {% trans "Efetuar Login" %} </h2>
      <p><label for="id_username">{% trans "Usuário" %}:</label> <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username"></p>
      <p><label for="id_password">{% trans "Senha" %}:</label> <input type="password" name="password" autocomplete="current-password" required id="id_password"></p>
      <button type="submit" name="button">Login</button> </br></br>
      <a href="/usuarios/resetPassword/"> {% trans "Esqueceu a senha?" %} <a>
  </form>
</div>
{% endblock %}