tutorial/alunos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('homeMaterias/', views.homeMaterias, name="homeMaterias"),
    path('cadastrarMateria/', views.cadastrarMateria, name="cadastrarMateria"),
    path('editarMateria/', views.editarMateria, name="editarMateria"),
    path('alterarMateria/', views.alterarMateria, name="alterarMateria"),
    path('editarMateria/<int:materia_id>/', views.editarMateria, name="editarMateria"),
    path('deleteMateria/<int:materia_id>/', views.deleteMateria, name="deleteMateria"),
    path('salvarAlteracoesMateria/<int:materia_id>/', views.salvarAlteracoesMateria, name="salvarAlteracoesMateria"),
    path('usuariosMaterias/', views.usuariosMaterias, name="usuariosMaterias"),
    path('salvarUsuariosMaterias/', views.salvarUsuariosMaterias, name="salvarUsuariosMaterias"),
    path('listarUsuariosMaterias/', views.listarUsuariosMaterias, name="listarUsuariosMaterias"),
    path('viewNotasUsuarios/', views.viewNotasUsuarios, name="viewNotasUsuarios"),
    path('filtrarNotasUsuarioData/', views.filtrarNotasUsuarioData, name="filtrarNotasUsuarioData"),
    path('filtrarNotasUsuario/', views.filtrarNotasUsuario, name="filtrarNotasUsuario"),
    path('listarMateriasNotas/', views.listarMateriasNotas, name="listarMateriasNotas"),
    path('deleteUsuarioMateria/<slug:username>/', views.deleteUsuarioMateria, name="deleteUsuarioMateria"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('editarMateriaUsuario/<slug:username>/', views.editarMateriaUsuario, name="editarMateriaUsuario"),
    path('salvarUserMaterias/<slug:username>/', views.salvarUserMaterias, name="salvarUserMaterias"),
    path('viewMateriasUsuario/<int:materia_id>/', views.viewMateriasUsuario, name="viewMateriasUsuario"),
    path('criarPergunta/', views.criarPergunta, name="criarPergunta"),
    path('inserirPergunta/', views.inserirPergunta, name="inserirPergunta"),
    path('listarPerguntasMateria/', views.listarPerguntasMateria, name="listarPerguntasMateria"),
    path('listarPerguntas/', views.listarPerguntas, name="listarPerguntas"),
    path('editarPergunta/<int:pergunta_id>/', views.editarPergunta, name="editarPergunta"),
    path('deletePergunta/<int:materia_id>/<int:pergunta_id>/', views.deletePergunta, name="deletePergunta"),
    path('salvarAlteracoesPergunta/<int:pergunta_id>/', views.salvarAlteracoesPergunta, name="salvarAlteracoesPergunta"),
    path('listarMateriasProva/', views.listarMateriasProva, name="listarMateriasProva"),
    path('listarAlunosMateria/', views.listarAlunosMateria, name="listarAlunosMateria"),
    path('criarProva/', views.criarProva, name="criarProva"),
    path('viewProvasAlunos/', views.viewProvasAlunos, name="viewProvasAlunos"),
    path('deleteProva/<int:materia_id>/<slug:usuario>/', views.deleteProva, name="deleteProva"),
    path('inicioProvaAluno/', views.inicioProvaAluno, name="inicioProvaAluno"),
    path('salvarProva/', views.salvarProva, name="salvarProva"),
    path('listarPerguntasProva/', views.listarPerguntasProva, name="listarPerguntasProva"),
    path('concluirProva/<nome_materia>/', views.concluirProva, name="concluirProva"),
    path('verProvaAluno/<int:materia_id>/<slug:usuario>/', views.verProvaAluno, name="verProvaAluno"),
    path('salvarCorrecoes/', views.salvarCorrecoes, name="salvarCorrecoes"),
    path('salvarNotaUsuario/<data>/<slug:aluno>/<int:prova_id>/', views.salvarNotaUsuario, name="salvarNotaUsuario"),
    path('arquivarProva/<int:materia_id>/<slug:aluno>/', views.arquivarProva, name="arquivarProva"),
    path('viewProvasHistory/', views.viewProvasHistory, name="viewProvasHistory"),
    path('mostrarDetalhesProva/<int:prova_id>/', views.mostrarDetalhesProva, name="mostrarDetalhesProva"),
    path('filtrarMateriaHistory/', views.filtrarMateriaHistory, name="filtrarMateriaHistory"),
    path('filtrarProvaAluno/', views.filtrarProvaAluno, name="filtrarProvaAluno")
]

tutorial/produtos/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from produtos import views
from produtos import apis

urlpatterns = [
    path('', views.homeProdutos, name="homeProdutos"),
    path('cadastrarProduto/', views.cadastrarProduto, name="cadastrarProduto"),
    path('editarProduto/<int:produto_id>/', views.editarProduto, name="editarProduto"),
    path('salvarAlteracoesProduto/<int:produto_id>/', views.salvarAlteracoesProduto, name="salvarAlteracoesProduto"),
    path('deleteProduto/<int:produto_id>/', views.deleteProduto, name="deleteProduto"),
    path('ativarProduto/', views.ativarProduto, name="ativarProduto"),
    path('salvarAtivarProduto/', views.salvarAtivarProduto, name="salvarAtivarProduto"),
    path('menuCategorias/', views.menuCategorias, name="menuCategorias"),
    path('viewDetalhesProduto/<int:produto_id>/', views.viewDetalhesProduto, name="viewDetalhesProduto"),
    path('viewProdutosCategoria/<int:cat_id>/', views.viewProdutosCategoria, name="viewProdutosCategoria"),
    path('recebeProdutos/', apis.recebeProdutos, name="recebeProdutos"),
    path('cadastrarCategoria/', views.cadastrarCategoria, name="cadastrarCategoria"),
    path('filtrarCategorias/', views.filtrarCategorias, name="filtrarCategorias"),
    path('categorias/', views.homeCategorias, name="homeCategorias"),
    path('editarCategoria/<int:cat_id>/', views.editarCategoria, name="editarCategoria"),
    path('deleteCategoria/<int:cat_id>/', views.deleteCategoria, name="deleteCategoria"),
    path('salvarAlteracoesCategoria/<int:cat_id>/', views.salvarAlteracoesCategoria, name="salvarAlteracoesCategoria"),
    path('recebeJsonCompleto/', apis.recebeJsonCompleto, name="recebeJsonCompleto"),
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from principal.views import home
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('principal.urls')),
    path('alunos/', include('alunos.urls')),
    path('tutorial/', home),
    path('usuarios/', include('usuarios.urls')),
    path('produtos/', include('produtos.urls')),
    path('principal/', include('principal.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('usuarios/login/', include('django.contrib.auth.urls'), name='login'),
    prefix_default_language=True,
)


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutorial/produtos/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):

    STATUS_CAT = (
        (u'ativa', u'Ativa'),
        (u'inativa', u'Inativa'),
    )
    SIGLA_IDIOMA = (
        (u'pt', u'pt'),
        (u'en', u'en'),
    )

    nome_categoria = models.CharField(max_length=30)
    des_categoria = models.CharField(max_length=50, blank=True, null=True)
    img_categoria = models.FileField(upload_to='produtos/produtos.images', blank=True, null=True)
    status_categoria = models.CharField(choices=STATUS_CAT, max_length=10, default=0)
    idioma = models.CharField(choices=SIGLA_IDIOMA, max_length=10)

    def __str__(self):
        return self.nome_categoria


class Produto(models.Model):
    STATUS_PROD = (
        (u'ativo', u'Ativo'),
        (u'inativo', u'Inativo'),
    )
    SIGLA_IDIOMA = (
        (u'pt', u'pt'),
        (u'en', u'en'),
    )

    nome_produto = models.CharField(max_length=50)
    codigo_produto = models.CharField(max_length=10, blank=True)
    descricao_produto = models.CharField(max_length=200, null=True, blank=True)
    preco_produto = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    img_produto = models.FileField(upload_to='produtos.images/', blank=True)
    status_produto = models.CharField(choices=STATUS_PROD, max_length=10, default=0)
    idioma = models.CharField(choices=SIGLA_IDIOMA, max_length=10)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

tutorial/produtos/forms.py
from django import forms
from django.forms import ModelForm
from .models import Produto, Categoria


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = [
            'id',
            'codigo_produto',
            'nome_produto',
            'descricao_produto',
            'preco_produto',
            'status_produto',
            'img_produto',
            'idioma',
            'categoria'
        ]

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = [
            'nome_categoria',
            'des_categoria',
            'status_categoria',
            'img_categoria',
            'idioma'
        ]

tutorial/produtos/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
import datetime
from django.utils import translation
from django.conf.urls import i18n
from django.db.models import Sum
from django.utils.translation import gettext as _
from .models import Produto, Categoria
from .forms import ProdutoForm, CategoriaForm
from .functions import (excluirProduto, getCategoriaProduto, getNomeCategoria, excluirCategoria,
    checkProdutoExiste, checkCategoriaExiste, getCategoriaId)
from principal.functions import getIdiomaSystem
from principal.models import SystemConfiguration
from pedidos.functions import getNrPedido

def homeProdutos(request):
    idioma = translation.get_language()
    produtos = Produto.objects.all()
    categorias = Categoria.objects.filter(idioma=idioma)
    context = {
        'produtos': produtos,
        'idioma': idioma,
        'categorias': categorias
    }
    return render(request, "produtos.html", context)

def filtrarCategorias(request):
    idioma = translation.get_language()
    categoria = request.POST.get("categoria")
    categorias = Categoria.objects.filter(idioma=idioma)
    produtos = Produto.objects.filter(categoria_id=categoria)
    context = {
        'produtos': produtos,
        'idioma': idioma,
        'categorias': categorias
    }
    return render(request, "produtos.html", context)

def cadastrarProduto(request):
    idioma = translation.get_language()
    idiomas = SystemConfiguration.objects.all()
    form = ProdutoForm(request.POST, request.FILES)
    categorias = Categoria.objects.filter(idioma=idioma)
    if form.is_valid():
        form.save()
        return redirect('/' + idioma + '/produtos/')
    else:
        form = ProdutoForm(request.POST, request.FILES)
        print("form is not valid")
        print(form.errors)
    context = {
        'form': form,
        'idiomas': idiomas,
        'categorias': categorias
    }
    return render(request, "cadastrarProduto.html", context)

def editarProduto(request, produto_id):
    produto = Produto.objects.get(id=produto_id)
    language = produto.idioma
    idiomas = SystemConfiguration.objects.exclude(codigo=language)
    categorias = Categoria.objects.all()
    cat_produto = getCategoriaProduto(request, produto_id)
    cat_id = cat_produto[0]['categoria_id']
    categoria = getNomeCategoria(request, cat_id)
    nome_categoria = categoria[0]['nome_categoria']
    categorias = Categoria.objects.exclude(nome_categoria=nome_categoria)
    context = {
        'produto': produto,
        'idiomas': idiomas,
        'categorias': categorias,
        'nome_categoria': nome_categoria
    }
    return render(request, "editarProduto.html", context)

def salvarAlteracoesProduto(request, produto_id):
    idioma = translation.get_language()
    produto = Produto.objects.get(id=produto_id)
    codigo_produto = request.POST.get("codigo_produto")
    nome_produto = request.POST.get("nome_produto")
    descricao_produto = request.POST.get("descricao_produto")
    preco_produto = request.POST.get("preco_produto")
    status_produto = request.POST.get("status_produto")
    img_produto = request.FILES.get("img_produto")
    idioma = request.POST.get("idioma")
    categoria = request.POST.get("categoria")
    produto.codigo_produto = codigo_produto
    produto.nome_produto = nome_produto
    produto.descricao_produto = descricao_produto
    produto.status_produto = status_produto
    produto.preco_produto = preco_produto
    produto.idioma = idioma
    produto.categoria_id = categoria
    if img_produto:
        produto.img_produto = img_produto
    produto.save()
    return redirect('/produtos/')

def deleteProduto(request, produto_id):
    idioma = translation.get_language()
    excluir = excluirProduto(request, produto_id)
    return redirect('/' + idioma + '/produtos/')

def ativarProduto(request):
    idioma = translation.get_language()
    produtos = Produto.objects.filter(status_produto="inativo")
    context = {
        'produtos': produtos,
        'idioma': idioma
    }
    return render(request, "ativarProduto.html", context)

def salvarAtivarProduto(request):
    produto_id = request.POST.get("nome_produto")
    produto = Produto.objects.get(id=produto_id)
    status_produto = request.POST.get("status_produto")
    produto.status_produto = status_produto
    produto.save()
    return redirect('/produtos/')

def menuCategorias(request):
    idioma = translation.get_language()
    categorias = Categoria.objects.all()
    context = {
        'categorias': categorias,
        'idioma': idioma
    }
    return render(request, "menuCategorias.html", context)

def viewDetalhesProduto(request, produto_id):
    idioma = translation.get_language()
    produto = Produto.objects.get(id=produto_id)
    context = {
        'produto': produto,
        'idioma': idioma
    }
    return render(request, "detalhesProduto.html", context)

def viewProdutosCategoria(request, cat_id):
    idioma = translation.get_language()
    produtos = Produto.objects.filter(categoria_id=cat_id)
    context = {
        'idioma': idioma,
        'produtos': produtos
    }
    return render(request, "listProdutos.html", context)

def cadastrarCategoria(request):
    idioma = translation.get_language()
    idiomas = SystemConfiguration.objects.all()
    form = CategoriaForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/' + idioma + '/produtos/menuCategorias/')
    else:
        form = CategoriaForm(request.POST, request.FILES)
        print("form is not valid")
        print(form.errors)
    context = {
        'form': form,
        'idiomas': idiomas
    }
    return render(request, "cadastrarCategoria.html", context)

def homeCategorias(request):
    idioma = translation.get_language()
    categorias = Categoria.objects.all()
    context = {
        'idioma': idioma,
        'categorias': categorias
    }
    return render(request, "categorias.html", context)

def editarCategoria(request, cat_id):
    categoria = Categoria.objects.get(id=cat_id)
    language = categoria.idioma
    idiomas = SystemConfiguration.objects.exclude(codigo=language)
    context = {
        'categoria': categoria,
        'idiomas': idiomas
    }
    return render(request, "editarCategoria.html", context)

def salvarAlteracoesCategoria(request, cat_id):
    categoria = Categoria.objects.get(id=cat_id)
    nome_categoria = request.POST.get("nome_categoria")
    descricao_categoria = request.POST.get("des_categoria")
    status_categoria = request.POST.get("status_categoria")
    img_categoria = request.FILES.get("img_categoria")
    idioma = request.POST.get("idioma")
    categoria.nome_categoria = nome_categoria
    categoria.des_categoria = descricao_categoria
    categoria.status_categoria = status_categoria
    if img_categoria:
        categoria.img_categoria = img_categoria
    categoria.idioma = idioma
    categoria.save()
    return redirect('/produtos/categorias/')

def deleteCategoria(request, cat_id):
    mensagem = ""
    idioma = translation.get_language()
    categorias = Categoria.objects.all()
    try:
        excluir = excluirCategoria(request, cat_id)
        mensagem = _("Categoria excluída com sucesso!")
    except Exception as ex:
        mensagem = _("Existem produtos associados a essa Categoria. Não é possível excluí-la")
    context = {
        'mensagem': mensagem,
        'idioma': idioma,
        'categorias': categorias
    }
    return render(request, "categorias.html", context)

tutorial/produtos/templates/ativarProduto.html
{% extends 'base.html' %}
{% load i18n %}

{% block body %}
<div class="container">
<form method="post" action="{% url 'salvarAtivarProduto' %}">
  {% csrf_token %}
      <p><label for="id_nome_produto">{% trans "Nome Produto" %}:</label> <select name="nome_produto" id="id_nome_produto">
      <option value="">--------</option>
      {% for produto in produtos %}
          <option value="{{ produto.id }}">{{ produto.nome_produto }}</option>
      {% endfor %}
    </select></p>
      <p><label for="id_status_produto">{% trans "Status Produto" %}:</label> <select name="status_produto" id="id_status_produto">
        <option value="">--------</option>
        <option value="ativo">{% trans "Ativo" %}</option>
        <option value="inativo">{% trans "Inativo" %}</option>
      <p><button type="submit"> {% trans "Salvar" %} </button><p>
</form>
</div>
{% endblock %}

tutorial/produtos/templates/cadastrarCategoria.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
<script>
function fileSelect(id, e){
    var filename = e.target.files[0].name;
    el = document.getElementById("arq-select");
  	$('#arq-select').html(filename);
};
</script>
{% endblock %}

{% block body %}
<div class="container">
  <h1> {% trans "Cadastro de Categoria" %} </h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
        <p><label for="id_nome_categoria">{% trans "Nome Categoria" %}:</label> <input type="text" name="nome_categoria" maxlength="30" required id="id_nome_categoria"></p>
        <p><label for="id_des_categoria">{% trans "Descrição Categoria" %}:</label> <input type="text" name="des_categoria" maxlength="50" id="id_des_categoria"></p>
        <p><label for="id_status_categoria">{% trans "Status Categoria" %}:</label> <select name="status_categoria" id="id_status_categoria">
            <option value="ativa">{% trans "Ativa" %}</option>
            <option value="inativa">{% trans "Inativa" %}</option>
        </select></p>
        <p><label for="id_img_categoria">{% trans "Imagem Categoria" %}:</label>
          <label for="img_categoria" class="btn-file">{% trans "Escolher arquivo" %}</label>
            <div id="arq-select"> {% trans "Nenhum arquivo selecionado" %} </div>
              <input id="img_categoria" type="file" name="img_categoria" onchange='fileSelect(img_categoria, event)' />
        <p><label for="id_idioma">{% trans "Idioma" %}:</label> <select name="idioma" required id="id_idioma">
          {% for idioma in idiomas %}
            <option value="{{ idioma.codigo }}"> {{idioma.codigo }} </option>
          {% endfor %}
        </select></p>
        <button type="submit"> {% trans "Cadastrar" %} </button>
    </form>
</div>
{% endblock %}

tutorial/produtos/templates/cadastrarProduto.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block head %}
<title> {% trans "Cadastro de Produtos" %} </title>
<script>
function fileSelect(id, e){
    var filename = e.target.files[0].name;
    el = document.getElementById("arq-select");
  	$('#arq-select').html(filename);
};
</script>
{% endblock %}


{% block body %}
<div class="container">
  <h1> {% trans "Cadastro de Produtos" %} </h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <p><label for="id_codigo_produto">{% trans "Código Produto" %}:</label> <input type="text" name="codigo_produto" maxlength="10" id="id_codigo_produto"></p>
      <p><label for="id_nome_produto">{% trans "Nome Produto" %}:</label> <input type="text" name="nome_produto" maxlength="50" required id="id_nome_produto"></p>
      <p><label for="id_descricao_produto">{% trans "Descrição Produto" %}:</label> <input type="text" name="descricao_produto" maxlength="200" id="id_descricao_produto"></p>
      <p><label for="id_preco_produto">{% trans "Preço Produto" %}:</label> <input type="number" name="preco_produto" step="0.01" id="id_preco_produto"></p>
      <p><label for="id_status_produto">{% trans "Status Produto" %}:</label> <select name="status_produto" id="id_status_produto">
          <option value="ativo">{% trans "Ativo" %}</option>
          <option value="inativo">{% trans "Inativo" %}</option>
      </select></p>
      <p><label for="id_img_produto">{% trans "Imagem Produto" %}:</label>
        <label for="img_produto" class="btn-file">{% trans "Escolher arquivo" %}</label>
          <div id="arq-select"> {% trans "Nenhum arquivo selecionado" %} </div>
            <input id="img_produto" type="file" name="img_produto" onchange='fileSelect(img_produto, event)' />
      <p><label for="id_idioma">{% trans "Idioma" %}:</label> <select name="idioma" required id="id_idioma">
        {% for idioma in idiomas %}
          <option value="{{ idioma.codigo }}"> {{idioma.codigo }} </option>
        {% endfor %}
      </select></p>
      <p><label for="id_categoria">{% trans "Categoria" %}:</label> <select name="categoria" required id="id_categoria">
          <option value="" selected>---------</option>
          {% for categoria in categorias %}
                <option value="{{categoria.id}}">{{categoria.nome_categoria}}</option>
          {% endfor %}
      </select></p>
        <button type="submit"> {% trans "Cadastrar" %} </button>
    </form>
</div>
{% endblock %}

tutorial/produtos/templates/detalhesProduto.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block body %}
    <div class="container">
       <a href="{% url 'viewProdutosCategoria' produto.categoria_id %}"> <button type="button"> {% trans "Voltar" %} </button> </a>
    </div>
    <form method="post" enctype="multipart/form-data" action="{% url 'adicionarProduto' produto.id %}">
      {% csrf_token %}
        <h1 class="titulo-produto"> {{ produto.nome_produto }} </h1>
        <img class="prod-det img" src="{{ produto.img_produto.url }}" alt="{{ produto.nome_produto }}" />
        <div class="descricao-produto">
          <p> <b> {% trans "Descrição" %}: </b> {{ produto.descricao_produto }} <p>
          <p> <b> {% trans "Preço" %}: </b> {{ produto.preco_produto }} </p>
          {% if request.user.is_authenticated %}
              <p> <b> {% trans "Quantidade" %}: </b> <input name="quantidade" type="number" size="2" min="1" max="20" value="1"> </p>
              <p> <button type="submit"> {% trans "Comprar" %} </button> </p>
          {% endif %}
        </div>
      </form>
{% endblock %}

tutorial/produtos/templates/editarCategoria.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block body %}
<div class="container">
  <h1> {% trans "Editar Categoria" %} </h1>
    <form method="post" enctype="multipart/form-data" action="{% url 'salvarAlteracoesCategoria' categoria.id %}">
      {% csrf_token %}
        <p><label for="id_nome_categoria">{% trans "Nome Categoria" %}:</label> <input type="text" name="nome_categoria" maxlength="30" required id="id_nome_categoria" value="{{ categoria.nome_categoria}}"></p>
        <p><label for="id_des_categoria">{% trans "Descrição Categoria" %}:</label> <input type="text" name="des_categoria" maxlength="50" id="id_des_categoria" value="{{ categoria.des_categoria}}"></p>
        <p><label for="id_status_categoria">{% trans "Status Categoria" %}:</label> <select name="status_categoria" id="id_status_categoria" value="{{ categoria.status_categoria}}">
            <option value="ativa">{% trans "Ativa" %}</option>
            <option value="inativa">{% trans "Inativa" %}</option>
        </select></p>
        <p><label for="id_img_categoria">{% trans "Imagem Categoria" %}:</label> <input type="file" name="img_categoria" id="id_img_categoria"></p>
        {% if categoria.img_categoria %}
            <p> <img width="200px" height="150px" src="{{categoria.img_categoria.url}}"/></td> </br>
        {% endif %}
        <p><label for="id_idioma">{% trans "Idioma" %}:</label> <select name="idioma" required id="id_idioma" value="{{ categoria.idioma}}">
            <option value="{{ categoria.idioma }}" selected>{{ categoria.idioma }}</option>
            {% for idioma in idiomas %}
              <option value="{{ idioma.codigo }}"> {{idioma.codigo }} </option>
            {% endfor %}
        </select></p>
        <button type="submit"> {% trans "Salvar Alterações" %} </button>
    </form>
</div>
{% endblock %}

tutorial/produtos/templates/editarProduto.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block body %}
<div class="container">
<h1> {% trans "Alteração de Produto" %} </h1>
  <form method="post" enctype="multipart/form-data" action="{% url 'salvarAlteracoesProduto' produto.id %}">
    {% csrf_token %}
      <p><label for="id_codigo_produto">{% trans "Código Produto" %}:</label> <input type="text" name="codigo_produto" maxlength="10" id="id_codigo_produto" value="{{ produto.codigo_produto }}"></p>
      <p><label for="id_nome_produto">{% trans "Nome Produto" %}:</label> <input type="text" name="nome_produto" maxlength="50" required id="id_nome_produto" value="{{ produto.nome_produto }}"></p>
      <p><label for="id_descricao_produto">{% trans "Descrição Produto" %}:</label> <input type="text" name="descricao_produto" maxlength="200" id="id_descricao_produto" value="{{ produto.descricao_produto }}"></p>
      <p><label for="id_preco_produto">{% trans "Preço Produto" %}:</label> <input type="decimal" name="preco_produto" step="0.01" id="id_preco_produto" value="{{ produto.preco_produto }}"></p>
      <p><label for="id_status_produto">{% trans "Status Produto" %}:</label> <select name="status_produto" id="id_status_produto" value="{{ produto.status_produto }}">
        <option value="ativo">{% trans "Ativo" %}</option>
        <option value="inativo">{% trans "Inativo" %}</option>
      </select></p>
      <p><label class="required" for="id_idioma">{% trans "Idioma" %}:</label>
      <select name="idioma" id="id_idioma" value="{{ produto.idioma }}">
          <option value="{{ produto.idioma }}" selected>{{ produto.idioma }}</option>
          {% for idioma in idiomas %}
            <option value="{{ idioma.codigo }}"> {{idioma.codigo }} </option>
          {% endfor %}
      </select></p>
      <p><label class="required" for="id_categoria">{% trans "Categoria" %}:</label>
        <select name="categoria" id="id_categoria">
          <option value="{{ produto.categoria_id }}" selected>{{ nome_categoria }}</option>
        {% for cat in categorias %}
          <option value="{{ cat.id }}">{{ cat.nome_categoria }}</option>
        {% endfor %}
      </select></p>
      <p><label for="id_img_produto">{% trans "Imagem Produto" %}:</label> <input type="file" name="img_produto" id="id_img_produto"></p>
      {% if produto.img_produto %}
          <p> <img width="200px" height="150px" src="{{produto.img_produto.url}}"/></td> </br>
      {% endif %}
      <p><button type="submit"> {% trans "Atualizar Cadastro" %} </button><p>
  </form>
</div>
{% endblock %}